name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt install -y build-essential cmake

    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --parallel

    - name: Run tests
      run: cd build && ctest --output-on-failure
