name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    container: nniikon/kolyagpt:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        cmake -B build -S .
        cmake --build build --parallel

    - name: Run tests
      run: cd build && ctest --output-on-failure
